### Input path
data_dir: # Defined from the scripts
input_file: # Defined from the scripts

### Output path
encode_save_dir:  # Defined from the scripts
ivf_dir: index
output_path: # Defined from the scripts

### Running arguments
base_model: castorini/ance-dpr-question-multi
batch_size: 64
search_topk: 10
dry_run: True
q_max_len: 32
dataloader_num_workers: 0

### Indexer specific arguments
search_batch_size: 2000
nlist: 65536
nprobe: 64