### Input path
data_dir: /workspaces/kvzip_nlplab/KFC/data/nq/raw
input_file: valid_with_id.jsonl # Defined from the scripts

### Output path
encode_save_dir: /workspaces/kvzip_nlplab/KFC/data/nq/retrieved_100 # Defined from the scripts
ivf_dir: /workspaces/kvzip_nlplab/ivf_dir
output_path: valid.jsonl # Defined from the scripts

### Running arguments
base_model: castorini/ance-dpr-question-multi
batch_size: 64
search_topk: 100
dry_run: True
q_max_len: 32
dataloader_num_workers: 0

### Indexer specific arguments
search_batch_size: 2000
nlist: 65536
nprobe: 64